### ISSUE TITLE
Criar healthcheck para o instrumento

### ISSUE THREAD

**Issue by Kovalski-rgb** [TCC-Pucpr/fed-inspirasom#19]
Ele vai retornar se o instrumento está ou não conectado no computador - resumindo, um boolean

**Comment by Knightleo602** [comment]
Eu vou fazer um novo evento que manda para o front se o instrumento foi desconectado/reconectado

**Comment by Knightleo602** [comment]
Se pa vamo ter essa limitacao por um tempo, as libs q usamos nao tem um sistema pra notificacao de desconecta

**Comment by Kovalski-rgb** [comment]
sem problemas, o intuito do healthcheck é pra ter um QoL caso o instrumento esteja com mal contato

**Comment by Knightleo602** [comment]
Vou fechar esse issue pois a chance de ser feita é baixa
