### ISSUE TITLE
Identificacao de erro, acerto, e criacao de um score

### ISSUE THREAD

**Issue by Knightleo602** [TCC-Pucpr/fed-inspirasom#60]

**Comment by Kovalski-rgb** [comment]
erro e acerto ja ta feito do lado do front (de maneira bem basica), o score ta bem primitivo, só leva em conta o multiplicador e se a nota foi acertada ou não

**Comment by Knightleo602** [comment]
Pra essa issue vou criar so o storage pro score de cada musica entao

**Comment by Kovalski-rgb** [comment]
Tenho uma sugestão em relação ao score
Acho que de inicio, podemos separar ele em pequenas partes, e decidir oq a gnt faz com ele depois.

- Tipo criar um valor que representa a precisão geral do cara com o acerto da nota (sei la, %tagem da precisão do cara na musica)
- Outro valor que representa quantas notas ele acertou em partes que vem mais notas em relação ao resto da musica
- Outro pega a média da pressão de ar, e o valor máximo que ele atingiu assoprando no instrumento

Ai no final a gnt trabalha com esses valores, variando com o objetivo da musica (ex. se o cara precisa passar de uma musica q vem poucas notas, mas elas vem de maneira rapida, faz mais sentido ter mais peso no primeiro valor, em relação aos outros)

**Comment by Kovalski-rgb** [comment]
> Pra essa issue vou criar so o storage pro score de cada musica entao  

Existe um esquema no lado do cliente chamado IndexedDB pra persistencia de dados (é uma feature pra browsers)
Dava pra gnt dar uma olhada nisso pra salvar esse tipo de coisa

**Comment by Knightleo602** [comment]
Usa o plugin do tauri: https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/store

**Comment by Knightleo602** [comment]
Reabri por causa da integracao com o front

**Comment by Kovalski-rgb** [comment]
qual integração exatamente?

**Comment by Kovalski-rgb** [comment]
> Reabri por causa da integracao com o front

cria uma nova issue especifica pra essa integração, fica mais simples de visualizar
