### ISSUE TITLE
Correcao build no ubuntu

### ISSUE THREAD

**Issue by Knightleo602** [TCC-Pucpr/fed-inspirasom#61]

**Comment by Kovalski-rgb** [comment]
Um pacote especifico chamado alsa-sys que ta impedindo a build, ele é uma suposta dependencia que não existe no ubuntu (mas por algum motivo passa sem problemas no windows)

**Comment by Knightleo602** [comment]
Tenta alguns dos comandos nessa thread aqui:
https://github.com/Spotifyd/spotifyd/issues/659

Pelo visto é alguma dependencia que nao ta instalado no teu Ubuntu
