### ISSUE TITLE
Atualizar versao do Tauri

### ISSUE THREAD

**Issue by Knightleo602** [TCC-Pucpr/fed-inspirasom#62]

**Comment by Knightleo602** [comment]
Tem nova versao do Tauri, podemos ver de atualizar para o 2.0 ja, que tem suporte pra mobile

**Comment by Kovalski-rgb** [comment]
só primeiro temos que veirificar se não vamos ter problemas de compatibilidade com a versão atual

A versão mobile está em alpha, não?

**Comment by Knightleo602** [comment]
Mobile ta junto com o 2.0, que recentemente saiu do alpha

**Comment by Knightleo602** [comment]
Vou fechar esse issue pois nao foi visto necessidade para atualizar o Tauri no momento
